# Generated by Django 2.1.5 on 2019-06-13 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_auto_20190515_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='action time')),
                ('message', models.TextField(blank=True, verbose_name='message')),
                ('action_flag', models.PositiveSmallIntegerField(choices=[(1, 'Authorization'), (2, 'Search'), (3, 'Logout')], verbose_name='action flag')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'main log',
                'verbose_name_plural': 'main logs',
                'ordering': ('-action_time',),
            },
        ),
    ]
