# Generated by Django 2.1.5 on 2019-06-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_mainlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainlog',
            name='client_address',
            field=models.TextField(blank=True, max_length=200, verbose_name='Адрес клиента'),
        ),
        migrations.AlterField(
            model_name='mainlog',
            name='action_flag',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Авторизация'), (2, 'Поиск'), (3, 'Выход из системы'), (4, 'Общий')], verbose_name='action flag'),
        ),
    ]
