# Generated by Django 2.1.5 on 2019-06-25 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190625_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainlog',
            name='client_address',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Адрес клиента'),
        ),
    ]
