# Generated by Django 2.1.5 on 2019-06-26 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190626_0157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainlog',
            options={'ordering': ('-action_time',), 'verbose_name': 'Лог активности', 'verbose_name_plural': 'Логи активности'},
        ),
        migrations.RemoveField(
            model_name='mainlog',
            name='action_flag',
        ),
    ]
