# Generated by Django 2.1.5 on 2019-09-29 23:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190626_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainlog',
            name='raw',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Голые данные'),
        ),
    ]
