# Generated by Django 2.1.5 on 2019-09-30 00:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_mainlog_raw'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='action time')),
                ('name', models.TextField(blank=True, max_length=50, null=True, verbose_name='Имя')),
                ('email', models.TextField(blank=True, max_length=100, null=True, verbose_name='Почта')),
                ('phone', models.TextField(blank=True, max_length=40, null=True, verbose_name='Телефон')),
                ('text', models.TextField(blank=True, max_length=500, null=True, verbose_name='Текст')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
