# Generated by Django 2.1.5 on 2019-10-07 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainlog',
            name='has_errors',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
