# Generated by Django 2.1.5 on 2019-10-07 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_mainlog_has_errors'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_subscriber',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
