# Generated by Django 2.1.5 on 2019-10-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_feedback_is_subscriber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ('-action_time',), 'verbose_name': 'Обратная связь', 'verbose_name_plural': 'Обратная связь'},
        ),
        migrations.AlterField(
            model_name='feedback',
            name='is_subscriber',
            field=models.BooleanField(default=False, null=True, verbose_name='Подписка'),
        ),
        migrations.AlterField(
            model_name='mainlog',
            name='client_address',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Адрес клиента'),
        ),
    ]
