# Generated by Django 2.2.10 on 2020-08-29 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20191030_1658'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ('-action_time',), 'verbose_name': 'Обратная связь/подписка', 'verbose_name_plural': 'Обратная связь/подписка'},
        ),
    ]
