# Generated by Django 2.1.5 on 2019-04-28 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='type',
            field=models.CharField(blank=True, choices=[('import', 'Импорт базы'), ('search', 'Поиск')], default='import', max_length=13, verbose_name='Тип файла'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='type',
            field=models.CharField(choices=[('hrd', 'жесткий'), ('sft', 'мягкий'), ('rcl', 'пересчет'), ('rlt', 'взаимосвязь'), ('prc', 'цена')], max_length=13, verbose_name='Тип'),
        ),
    ]
