# Generated by Django 2.1.5 on 2019-05-15 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20190428_0010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datafile',
            options={'ordering': ('updated_at',), 'verbose_name': 'Файл', 'verbose_name_plural': 'Файлы'},
        ),
    ]
