# Generated by Django 2.1.5 on 2019-05-17 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0003_auto_20190515_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedAttributeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Когда обновлено')),
                ('is_public', models.BooleanField(default=True, verbose_name='Опубликовано?')),
                ('deleted', models.BooleanField(default=False, editable=False, verbose_name='В архиве?')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fixed_values', to='catalog.Attribute', verbose_name='Атрибут')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кем создано')),
            ],
            options={
                'verbose_name': 'Значение атрибута(фикс)',
                'verbose_name_plural': 'Значения атрибутов(фикс)',
            },
        ),
        migrations.CreateModel(
            name='FixedValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Когда обновлено')),
                ('is_public', models.BooleanField(default=True, verbose_name='Опубликовано?')),
                ('deleted', models.BooleanField(default=False, editable=False, verbose_name='В архиве?')),
                ('title', models.CharField(max_length=255, verbose_name='Значение')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fixed_value', to='catalog.Attribute', verbose_name='Атрибут')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кем создано')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кем обновлено')),
            ],
            options={
                'verbose_name': 'Базовая модель ',
                'verbose_name_plural': 'Базовые модели',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UnFixedAttributeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Когда обновлено')),
                ('is_public', models.BooleanField(default=True, verbose_name='Опубликовано?')),
                ('deleted', models.BooleanField(default=False, editable=False, verbose_name='В архиве?')),
                ('value', models.FloatField(verbose_name='Нефикс значение атрибута')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unfixed_values', to='catalog.Attribute', verbose_name='Атрибут')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кем создано')),
            ],
            options={
                'verbose_name': 'Значение атрибута(нефикс)',
                'verbose_name_plural': 'Значения атрибутов(нефикс)',
            },
        ),
        migrations.RemoveField(
            model_name='attributevalue',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='attributevalue',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='attributevalue',
            name='products',
        ),
        migrations.RemoveField(
            model_name='attributevalue',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='product',
            name='attrs_vals',
        ),
        migrations.DeleteModel(
            name='AttributeValue',
        ),
        migrations.AddField(
            model_name='unfixedattributevalue',
            name='products',
            field=models.ManyToManyField(blank=True, to='catalog.Product'),
        ),
        migrations.AddField(
            model_name='unfixedattributevalue',
            name='updated_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кем обновлено'),
        ),
        migrations.AddField(
            model_name='fixedattributevalue',
            name='products',
            field=models.ManyToManyField(blank=True, to='catalog.Product'),
        ),
        migrations.AddField(
            model_name='fixedattributevalue',
            name='updated_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кем обновлено'),
        ),
        migrations.AddField(
            model_name='fixedattributevalue',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.FixedValue', verbose_name='Фиксированное значение атрибута'),
        ),
        migrations.AddField(
            model_name='product',
            name='fixed_attrs_vals',
            field=models.ManyToManyField(to='catalog.FixedAttributeValue', verbose_name='Фикс атрибуты'),
        ),
        migrations.AddField(
            model_name='product',
            name='unfixed_attrs_vals',
            field=models.ManyToManyField(to='catalog.UnFixedAttributeValue', verbose_name='Нефикс атрибуты'),
        ),
    ]
