# Generated by Django 2.1.5 on 2019-04-01 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_datafile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datafile',
            options={'verbose_name': 'Файл', 'verbose_name_plural': 'Файлы'},
        ),
        migrations.RemoveField(
            model_name='datafile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='datafile',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='datafile',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='datafile',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='datafile',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='datafile',
            name='updated_by',
        ),
    ]
