# Generated by Django 2.1.5 on 2019-06-13 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20190517_0310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fixedvalue',
            options={'verbose_name': 'Фиксированное значение', 'verbose_name_plural': 'Фиксированные значения'},
        ),
        migrations.AlterField(
            model_name='datafile',
            name='type',
            field=models.CharField(blank=True, choices=[('import', 'Импорт базы'), ('search', 'Поиск'), ('result_search', 'Результат поиска')], default='import', max_length=13, verbose_name='Тип файла'),
        ),
    ]
