# Generated by Django 2.1.5 on 2019-07-10 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20190613_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additional_article',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Доп. артикул'),
        ),
        migrations.AddField(
            model_name='product',
            name='series',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Серия'),
        ),
    ]
