# Generated by Django 2.1.5 on 2019-08-08 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20190711_0123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datafile',
            options={'ordering': ('-updated_at',), 'verbose_name': 'Файл', 'verbose_name_plural': 'Файлы'},
        ),
        migrations.AddField(
            model_name='product',
            name='is_duplicate',
            field=models.BooleanField(default=False, verbose_name='Дубликат'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_tried',
            field=models.BooleanField(default=False, verbose_name='Проверенный'),
        ),
    ]
