# Generated by Django 2.1.5 on 2019-04-01 00:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0006_auto_20190401_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Когда создано'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datafile',
            name='created_by',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кем создано'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datafile',
            name='deleted',
            field=models.BooleanField(default=False, editable=False, verbose_name='В архиве?'),
        ),
        migrations.AddField(
            model_name='datafile',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Опубликовано?'),
        ),
        migrations.AddField(
            model_name='datafile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Когда обновлено'),
        ),
        migrations.AddField(
            model_name='datafile',
            name='updated_by',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кем обновлено'),
            preserve_default=False,
        ),
    ]
