# Generated by Django 2.1.5 on 2019-04-06 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20190401_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='type',
            field=models.CharField(choices=[('hrd', 'жесткий'), ('sft', 'мягкий'), ('rcl', 'Пересчет'), ('rlt', 'Взаимосвязь'), ('prc', 'Цена')], max_length=13, verbose_name='Тип'),
        ),
    ]
