# Generated by Django 2.1.5 on 2019-08-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20190808_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedattributevalue',
            name='is_tried',
            field=models.BooleanField(default=False, verbose_name='Проверенный'),
        ),
        migrations.AddField(
            model_name='unfixedattributevalue',
            name='is_tried',
            field=models.BooleanField(default=False, verbose_name='Проверенный'),
        ),
    ]
