# Generated by Django 2.1.5 on 2019-11-25 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20190912_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='is_tried',
            field=models.BooleanField(default=False, verbose_name='Проверенный'),
        ),
    ]
