# Generated by Django 2.1.5 on 2020-03-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_product_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-priority',), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='product',
            name='is_updated',
            field=models.BooleanField(default=False, verbose_name='Обновлённый'),
        ),
    ]
