# Generated by Django 2.1.5 on 2020-03-27 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_auto_20200327_0500'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fixedvalue',
            options={'verbose_name': 'Фикс значение', 'verbose_name_plural': 'Фикс значения'},
        ),
        migrations.AddField(
            model_name='fixedvalue',
            name='image',
            field=models.ImageField(null=True, upload_to='images', verbose_name='Изображение'),
        ),
    ]
