# Generated by Django 2.2.10 on 2020-03-28 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_auto_20200328_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupsubclass',
            name='fixed_attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.FixedValue', verbose_name='Значение аттрибута'),
        ),
        migrations.AlterField(
            model_name='groupsubclass',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Изображение'),
        ),
    ]
