# Generated by Django 2.2.10 on 2020-07-10 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0020_auto_20200328_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Когда обновлено')),
                ('is_public', models.BooleanField(default=True, verbose_name='Опубликовано?')),
                ('deleted', models.BooleanField(default=False, editable=False, verbose_name='В архиве?')),
                ('is_fixed', models.BooleanField(default=False, verbose_name='Fixed value?')),
                ('un_value', models.FloatField(null=True, verbose_name='Нефиксированное значение атрибута')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.Attribute', verbose_name='Атрибут')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кем создано')),
            ],
            options={
                'verbose_name': 'Значение атрибута',
                'verbose_name_plural': 'Значения атрибутов',
            },
        ),
        migrations.RemoveField(
            model_name='unfixedattributevalue',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='unfixedattributevalue',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='unfixedattributevalue',
            name='products',
        ),
        migrations.RemoveField(
            model_name='unfixedattributevalue',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='category',
            name='level',
        ),
        migrations.RemoveField(
            model_name='category',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='category',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='category',
            name='tree_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fixed_attrs_vals',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unfixed_attrs_vals',
        ),
        migrations.DeleteModel(
            name='FixedAttributeValue',
        ),
        migrations.DeleteModel(
            name='UnFixedAttributeValue',
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Product'),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='updated_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кем обновлено'),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.FixedValue', verbose_name='Фиксированное значение атрибута'),
        ),
    ]
