# Generated by Django 2.2.10 on 2020-07-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_auto_20200710_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributevalue',
            name='is_fixed',
        ),
        migrations.AddField(
            model_name='attribute',
            name='is_fixed',
            field=models.BooleanField(default=False, verbose_name='Fixed attribute?'),
        ),
    ]
