# Generated by Django 2.2.10 on 2020-08-29 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_product_analogs_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='weight',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Вес'),
        ),
    ]
