# Generated by Django 2.2.10 on 2020-10-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_auto_20200911_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='irrelevant',
            field=models.BooleanField(default=False, verbose_name='Неактуал'),
        ),
    ]
