# Generated by Django 2.2.10 on 2020-10-15 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0026_product_irrelevant'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlternativeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Когда обновлено')),
                ('is_public', models.BooleanField(default=True, verbose_name='Опубликовано?')),
                ('deleted', models.BooleanField(default=False, editable=False, verbose_name='В архиве?')),
                ('alternative', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alternative_category', to='catalog.Category', verbose_name='Альтернативный класс')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кем создано')),
                ('original', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='original_category', to='catalog.Category', verbose_name='Исходный класс')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кем обновлено')),
            ],
            options={
                'verbose_name': 'Базовая модель ',
                'verbose_name_plural': 'Базовые модели',
                'abstract': False,
            },
        ),
    ]
